name: chatbot
description: "Engage in lively conversations with your personal AI companion through this sleek chatbot, featuring a striking black and green interface and seamless interaction."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  http: ^1.0.0
  shared_preferences: ^2.0.0
  smooth_page_indicator: ^1.0.0
  go_router: ^17.0.0
  url_launcher: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/onb1.gif
    - assets/onb2.png
    - assets/onb3.png
    - assets/bkg.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/onb3.png
  remove_alpha_ios: true
